In [ ]:
# Sumani
# 22-7-2024

# Tensor Exercises

# 1. Tensor Creation

In [1]:
import torch

In [4]:
# Create a tensor of shape (2, 4) filled with ones.

In [6]:
one_t = torch.ones((2, 4))
print(one_t)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
# Create a tensor of shape (5, 3) filled with random values.

In [10]:
random_t = torch.rand((5, 3))
print(random_t)

tensor([[0.4634, 0.9978, 0.9005],
        [0.0970, 0.3756, 0.1402],
        [0.8521, 0.2165, 0.3525],
        [0.4548, 0.5381, 0.2697],
        [0.4772, 0.4799, 0.3825]])


In [ ]:
# Create a tensor from a list [5, 10, 15, 20].

In [12]:
list_t = torch.tensor([5,10,15,20])
print(list_t)

tensor([ 5, 10, 15, 20])


In [ ]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.

In [17]:
# rows = height = 6
# coulms = width = 8
# Channels = RGB

image_t = torch.rand(3,6,8)
print(image_t)

tensor([[[5.4488e-01, 5.8493e-01, 6.2084e-01, 6.7044e-01, 7.3666e-02,
          5.2384e-01, 1.3389e-01, 7.7757e-01],
         [9.2188e-01, 7.7385e-01, 9.2564e-01, 1.5287e-01, 8.7565e-01,
          6.1252e-01, 9.3934e-01, 7.4349e-02],
         [4.2523e-01, 3.8157e-01, 7.4506e-01, 1.1826e-01, 2.3307e-01,
          4.6049e-01, 4.0529e-01, 2.7416e-01],
         [4.8106e-01, 6.0133e-01, 1.2200e-01, 4.3767e-02, 1.5502e-01,
          1.2956e-01, 4.3354e-01, 5.9224e-01],
         [6.0220e-01, 2.4928e-02, 9.7615e-01, 6.0335e-01, 3.1997e-01,
          6.4643e-01, 8.0699e-01, 8.8137e-01],
         [7.1784e-01, 1.6565e-01, 1.3044e-01, 9.8919e-01, 3.9209e-02,
          5.4218e-01, 6.7130e-01, 1.9324e-01]],

        [[2.9037e-01, 3.8646e-01, 9.7543e-01, 6.5223e-01, 3.8586e-01,
          4.9153e-01, 2.0172e-01, 1.4991e-01],
         [7.1383e-02, 5.5062e-01, 8.0799e-01, 2.8153e-01, 7.3645e-01,
          4.0065e-01, 3.4036e-01, 1.7993e-01],
         [4.5781e-02, 2.1953e-01, 6.7736e-02, 4.5039e-01, 7.03

# 2. Tensor Indexing and Slicing

In [ ]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.


In [19]:
t_range = torch.arange(10, 22).reshape(3, 4)
print(t_range)

tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])


In [ ]:
# Access the element at the second row, third column.

In [27]:
# Index for the n-th position is always n-1 due to zero-based indexing

print("Element at the 2nd row, 3rd column: ", t_range[1,2])

Element at the 2nd row, 3rd column:  tensor(16)


In [ ]:
# Print the second row.

In [28]:
print("2nd row: ", t_range[1])

2nd row:  tensor([14, 15, 16, 17])


In [ ]:
# Print the first two columns.

In [31]:
#: selects all rows
#:2 selects columns at index 0 and 1 (the first two columns)

print("First two columns: ",t_range[:,:2])

First two columns:  tensor([[10, 11],
        [14, 15],
        [18, 19]])


# 3. Tensor Arithmetic Operations

In [ ]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random values.

In [ ]:
# Perform element-wise addition.

In [ ]:
# Perform element-wise multiplication.

In [ ]:
# Subtract tensor_b from tensor_a.

# 4. Tensor Aggregation Operations

In [ ]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.

In [ ]:
# Compute the sum of all elements.

In [ ]:
# Compute the mean of all elements.

In [ ]:
# Find the maximum and minimum values.

In [ ]:
# Compute the sum along the rows.

In [ ]:
# Compute the mean along the columns.

# 5. Tensor Reshaping Operations

In [ ]:
# Create a tensor tensor of shape (2, 3, 4) with random values.

In [ ]:
# Reshape the tensor to (4, 6).

In [ ]:
# Transpose the tensor (swap the first and second dimensions).

In [ ]:
# Flatten the tensor to a 1D tensor.

# 6. Tensor Broadcasting

In [ ]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.

In [ ]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].

In [ ]:
# Perform broadcasting addition.

In [ ]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].

In [ ]:
# Perform broadcasting multiplication.

# 7. Tensor Device Management

In [ ]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).

In [ ]:
# Verify if the tensor is on GPU.
# Move the tensor back to CPU.

# 8. Tensor Cloning and Detaching

In [ ]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.

In [ ]:
# Clone the tensor and print the cloned tensor.

In [ ]:
# Detach the tensor from the computation graph and print the detached tensor.

# 9. High Dimensional Tensors

In [ ]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.

In [ ]:
# Print the shape of the tensor.

In [ ]:
# Access the element at position (1, 2, 3, 4).

In [ ]:
# Slice and print the first two elements along the first dimension.

In [ ]:
# Sum all elements in the tensor.

In [ ]:
# Compute the mean along the third dimension.

# 10. Combining Tensor Operations

In [ ]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.

In [ ]:
# Add the two tensors.

In [ ]:
# Multiply the resulting tensor by 2.

In [ ]:
# Reshape the tensor to (4, 6).

In [ ]:
# Compute the sum along the columns.

-------------------------------------------- END ----------------------------------------------