In [43]:
# Sumani
# 22-7-2024

# Tensor Exercises

# 1. Tensor Creation

In [44]:
import torch

In [45]:
# Create a tensor of shape (2, 4) filled with ones.

In [46]:
one_t = torch.ones((2, 4))
print(one_t)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [47]:
# Create a tensor of shape (5, 3) filled with random values.

In [48]:
random_t = torch.rand((5, 3))
print(random_t)

tensor([[0.0968, 0.9286, 0.5263],
        [0.2373, 0.8014, 0.7398],
        [0.6465, 0.2850, 0.3048],
        [0.1253, 0.7674, 0.4311],
        [0.1229, 0.3574, 0.0705]])


In [49]:
# Create a tensor from a list [5, 10, 15, 20].

In [50]:
list_t = torch.tensor([5,10,15,20])
print(list_t)

tensor([ 5, 10, 15, 20])


In [51]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.

In [52]:
# rows = height = 6
# coulms = width = 8
# Channels = RGB

image_t = torch.rand(3,6,8)
print(image_t)

tensor([[[0.2704, 0.9827, 0.2368, 0.5322, 0.4335, 0.8484, 0.2223, 0.9426],
         [0.0989, 0.8282, 0.0131, 0.8278, 0.7442, 0.5625, 0.6022, 0.0770],
         [0.2537, 0.8592, 0.9288, 0.3049, 0.2329, 0.1269, 0.2844, 0.4312],
         [0.2979, 0.8412, 0.5970, 0.4171, 0.5487, 0.1153, 0.1022, 0.3497],
         [0.6592, 0.0232, 0.2667, 0.8978, 0.9063, 0.0840, 0.6394, 0.8223],
         [0.3007, 0.6247, 0.4697, 0.2672, 0.3516, 0.3675, 0.9434, 0.7766]],

        [[0.8694, 0.3174, 0.8162, 0.1113, 0.4805, 0.1760, 0.6742, 0.7134],
         [0.3651, 0.3182, 0.1182, 0.9406, 0.2694, 0.8123, 0.6044, 0.9795],
         [0.8031, 0.8660, 0.9707, 0.9709, 0.3925, 0.1048, 0.5647, 0.0809],
         [0.2031, 0.3417, 0.7728, 0.9963, 0.8851, 0.3483, 0.5081, 0.9204],
         [0.4542, 0.3931, 0.7479, 0.4398, 0.6588, 0.0590, 0.2026, 0.2117],
         [0.2961, 0.4968, 0.4380, 0.0325, 0.6358, 0.5509, 0.1549, 0.9121]],

        [[0.3460, 0.4260, 0.9235, 0.8178, 0.1622, 0.2201, 0.0144, 0.0297],
         [0.0960, 0.0

# 2. Tensor Indexing and Slicing

In [53]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.


In [54]:
t_range = torch.arange(10, 22).reshape(3, 4)
print(t_range)

tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])


In [55]:
# Access the element at the second row, third column.

In [56]:
# Index for the n-th position is always n-1 due to zero-based indexing

print("Element at the 2nd row, 3rd column: ", t_range[1,2])

Element at the 2nd row, 3rd column:  tensor(16)


In [57]:
# Print the second row.

In [58]:
print("2nd row: ", t_range[1])

2nd row:  tensor([14, 15, 16, 17])


In [59]:
# Print the first two columns.

In [60]:
#: selects all rows
#:2 selects columns at index 0 and 1 (the first two columns)

print("First two columns: ",t_range[:,:2])

First two columns:  tensor([[10, 11],
        [14, 15],
        [18, 19]])


# 3. Tensor Arithmetic Operations

In [61]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random values.

In [62]:
tensor_a = torch.randint(1,100,(3,3))
tensor_b = torch.randint(1,100,(3,3))


print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)

Tensor A:
 tensor([[ 6,  7, 46],
        [82, 69, 59],
        [36, 78, 59]])
Tensor B:
 tensor([[91, 10, 73],
        [47, 88, 17],
        [19, 39, 38]])


In [63]:
# Perform element-wise addition.

In [64]:
tensor_add = tensor_a + tensor_b
print("tensor_a + tensor_b = \n ", tensor_add)

tensor_add_2= torch.add(tensor_a, tensor_b)

print("tensor_a + tensor_b = \n ", tensor_add_2)


tensor_a + tensor_b = 
  tensor([[ 97,  17, 119],
        [129, 157,  76],
        [ 55, 117,  97]])
tensor_a + tensor_b = 
  tensor([[ 97,  17, 119],
        [129, 157,  76],
        [ 55, 117,  97]])


In [65]:
# Perform element-wise multiplication.

In [66]:
tensor_mul = tensor_a * tensor_b
print("tensor_a x tensor_b = \n ", tensor_mul)

tensor_mul_2= torch.mul(tensor_a, tensor_b)
print("tensor_a x tensor_b = \n ", tensor_mul_2)


tensor_mul_3= torch.multiply(tensor_a, tensor_b)
print("tensor_a x tensor_b = \n ", tensor_mul_3)

tensor_a x tensor_b = 
  tensor([[ 546,   70, 3358],
        [3854, 6072, 1003],
        [ 684, 3042, 2242]])
tensor_a x tensor_b = 
  tensor([[ 546,   70, 3358],
        [3854, 6072, 1003],
        [ 684, 3042, 2242]])
tensor_a x tensor_b = 
  tensor([[ 546,   70, 3358],
        [3854, 6072, 1003],
        [ 684, 3042, 2242]])


In [67]:
# Subtract tensor_b from tensor_a.

In [68]:
tensor_sub = tensor_a - tensor_b
print("tensor_a - tensor_b = \n ", tensor_sub)

tensor_sub_2= torch.sub(tensor_a, tensor_b)

print("tensor_a - tensor_b = \n ", tensor_sub_2)

tensor_a - tensor_b = 
  tensor([[-85,  -3, -27],
        [ 35, -19,  42],
        [ 17,  39,  21]])
tensor_a - tensor_b = 
  tensor([[-85,  -3, -27],
        [ 35, -19,  42],
        [ 17,  39,  21]])


# 4. Tensor Aggregation Operations

In [69]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.

In [70]:
tensor_agg = torch.arange(1, 10).reshape(3, 3)

print("tensor of shape (3, 3) with values ranging from 1 to 9: \n", tensor_agg)

tensor of shape (3, 3) with values ranging from 1 to 9: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [71]:
# Compute the sum of all elements.

In [72]:
sum = torch.sum(tensor_agg)
print("Sum =", sum.item())

Sum = 45


In [73]:
# Compute the mean of all elements.

In [74]:
mean = tensor_agg.float().mean()
print("Mean :", mean.item())

Mean : 5.0


In [75]:
# Find the maximum and minimum values.

In [76]:
max = tensor_agg.max()
print("max :", max.item())

max : 9


In [77]:
# Compute the sum along the rows.

In [78]:
#dim=0: sum down the rows (column-wise)

#dim=1: sum across the columns (row-wise)

sum_rows = torch.sum(tensor_agg,dim=1)
print(sum_rows)

tensor([ 6, 15, 24])


In [79]:
# Compute the mean along the columns.

In [80]:
print(tensor_agg)
mean_col = tensor_agg.float().mean(dim=0)
print("Mean along columns:\n", mean_col)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Mean along columns:
 tensor([4., 5., 6.])


# 5. Tensor Reshaping Operations

In [81]:
# Create a tensor tensor of shape (2, 3, 4) with random values.

In [82]:
tensor_x = torch.randint(1000,(2,3,4))
print(tensor_x)

tensor([[[937, 948, 417,  44],
         [782, 994, 421,  56],
         [459, 505, 171, 597]],

        [[771, 965, 379, 172],
         [770, 680, 520, 920],
         [104, 167,  17, 789]]])


In [83]:
# Reshape the tensor to (4, 6).

In [84]:
tensor_reshape = tensor_x.reshape(4,6)
print(tensor_reshape)

tensor([[937, 948, 417,  44, 782, 994],
        [421,  56, 459, 505, 171, 597],
        [771, 965, 379, 172, 770, 680],
        [520, 920, 104, 167,  17, 789]])


In [85]:
# Transpose the tensor (swap the first and second dimensions).

In [86]:
tensor_transpose = tensor_reshape.T
print(tensor_transpose)

tensor_transpose2 = tensor_reshape.transpose(0, 1)
print(tensor_transpose2)

tensor([[937, 421, 771, 520],
        [948,  56, 965, 920],
        [417, 459, 379, 104],
        [ 44, 505, 172, 167],
        [782, 171, 770,  17],
        [994, 597, 680, 789]])
tensor([[937, 421, 771, 520],
        [948,  56, 965, 920],
        [417, 459, 379, 104],
        [ 44, 505, 172, 167],
        [782, 171, 770,  17],
        [994, 597, 680, 789]])


In [87]:
# Flatten the tensor to a 1D tensor.

In [88]:
tensor_1d = tensor_transpose.reshape(24)
print(tensor_1d)

flattened = tensor_transpose.flatten()
print(flattened)


tensor([937, 421, 771, 520, 948,  56, 965, 920, 417, 459, 379, 104,  44, 505,
        172, 167, 782, 171, 770,  17, 994, 597, 680, 789])
tensor([937, 421, 771, 520, 948,  56, 965, 920, 417, 459, 379, 104,  44, 505,
        172, 167, 782, 171, 770,  17, 994, 597, 680, 789])


# 6. Tensor Broadcasting

In [89]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.

In [90]:
tensor_a = torch.arange(1,7).reshape(2,3)
print(tensor_a)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [91]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].

In [92]:
tensor_b = torch.tensor([[1,2,3]])
print(tensor_b)
print(tensor_b.shape)

tensor([[1, 2, 3]])
torch.Size([1, 3])


In [93]:
# Perform broadcasting addition.

In [94]:
# tensor_b gets broadcast to shape (2, 3)
# Broadcasting addition
# Last dimension: 3 and 3 → equal
# Second-to-last dimension: 2 and 1 →  one dimension is 1 → broadcastable

tensor_add = tensor_a + tensor_b
print("tensor_a + tensor_b = ",tensor_add)


tensor_a + tensor_b =  tensor([[2, 4, 6],
        [5, 7, 9]])


In [95]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].

In [96]:
tensor_c = torch.tensor([1,2,3]).reshape(3,1)
print(tensor_c)

tensor([[1],
        [2],
        [3]])


In [97]:
# Perform broadcasting multiplication.

In [98]:
#tensor_c: shape (3, 1) → broadcast to (3, 3)
#tensor_b: shape (1, 3) → broadcast to (3, 3)

result = tensor_b * tensor_c
print("Result:\n", result)

Result:
 tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])


# 7. Tensor Device Management

In [99]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).

In [100]:
# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [101]:
# Create tensor and move to the appropriate device
tensor_gpu = torch.randint(100,(3,3)).to("cuda")
print(tensor_gpu)

tensor([[52,  5, 98],
        [92, 43, 40],
        [20, 90, 28]], device='cuda:0')


In [102]:
# Verify if the tensor is on GPU.
# Move the tensor back to CPU.

In [103]:
print("Tensor on device:", tensor_gpu.device)

Tensor on device: cuda:0


In [104]:
tensor_cpu = tensor_gpu.to("cpu")
print("Tensor on device:", tensor_cpu.device)
print(tensor_cpu)


Tensor on device: cpu
tensor([[52,  5, 98],
        [92, 43, 40],
        [20, 90, 28]])


# 8. Tensor Cloning and Detaching

In [105]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.

In [106]:
tensor_x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
print(tensor_x)

tensor([1., 2., 3.], requires_grad=True)


In [107]:
# Clone the tensor and print the cloned tensor.

In [108]:
cloned_tensor = tensor_x.clone()
print("Cloned Tensor:", cloned_tensor)

Cloned Tensor: tensor([1., 2., 3.], grad_fn=<CloneBackward0>)


In [109]:
# Detach the tensor from the computation graph and print the detached tensor.

In [110]:
detached_tensor = tensor_x.detach()
print("Detached Tensor:", detached_tensor)

Detached Tensor: tensor([1., 2., 3.])


# 9. High Dimensional Tensors

In [111]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.

In [112]:
tensor_4d = torch.randint(1000,(2, 3, 4, 5))
print(tensor_4d)

tensor([[[[780, 977, 134, 682, 870],
          [510, 486, 915, 317, 803],
          [950,   0,  61, 905,  22],
          [815, 689, 867,  12, 475]],

         [[139, 662, 310, 246,  90],
          [489, 527, 350,  11, 288],
          [226, 243, 241, 655, 620],
          [956, 918, 392, 935, 114]],

         [[231,  88, 965,  94, 986],
          [565, 323, 279,  61, 419],
          [972, 459, 962, 439, 443],
          [927, 695, 256, 355, 778]]],


        [[[758, 750, 887, 997, 101],
          [186, 191, 232, 596, 106],
          [ 66, 120, 309, 604, 723],
          [652, 656, 871, 456, 968]],

         [[  2, 938, 263, 855, 402],
          [136, 928, 781, 160,  85],
          [115, 403, 171, 676,  48],
          [988, 258, 765, 829, 749]],

         [[710, 129, 101, 919,  36],
          [669, 211, 577, 851, 442],
          [986, 953, 161, 868, 133],
          [ 45, 293, 541, 251, 276]]]])


In [113]:
# Print the shape of the tensor.

In [114]:
print(tensor_4d.shape)

torch.Size([2, 3, 4, 5])


In [115]:
# Access the element at position (1, 2, 3, 4).

In [116]:
print("Element at position (1, 2, 3, 4): ", tensor_4d[1,2,3,4])

Element at position (1, 2, 3, 4):  tensor(276)


In [117]:
# Slice and print the first two elements along the first dimension.

In [118]:
sliced = tensor_4d[:2]
print("Sliced Tensor (first two elements along dim 0):\n", sliced)

Sliced Tensor (first two elements along dim 0):
 tensor([[[[780, 977, 134, 682, 870],
          [510, 486, 915, 317, 803],
          [950,   0,  61, 905,  22],
          [815, 689, 867,  12, 475]],

         [[139, 662, 310, 246,  90],
          [489, 527, 350,  11, 288],
          [226, 243, 241, 655, 620],
          [956, 918, 392, 935, 114]],

         [[231,  88, 965,  94, 986],
          [565, 323, 279,  61, 419],
          [972, 459, 962, 439, 443],
          [927, 695, 256, 355, 778]]],


        [[[758, 750, 887, 997, 101],
          [186, 191, 232, 596, 106],
          [ 66, 120, 309, 604, 723],
          [652, 656, 871, 456, 968]],

         [[  2, 938, 263, 855, 402],
          [136, 928, 781, 160,  85],
          [115, 403, 171, 676,  48],
          [988, 258, 765, 829, 749]],

         [[710, 129, 101, 919,  36],
          [669, 211, 577, 851, 442],
          [986, 953, 161, 868, 133],
          [ 45, 293, 541, 251, 276]]]])


**sliced result is identical to the original tensor**

In [119]:
# Sum all elements in the tensor.

In [120]:
total_sum = tensor_4d.sum()
print("Sum of all elements:", total_sum.item())


Sum of all elements: 58912


In [121]:
# Compute the mean along the third dimension.

In [122]:
mean_dim3 = tensor_4d.float().mean(dim=2)
print("Mean along third dimension:\n", mean_dim3)


Mean along third dimension:
 tensor([[[763.7500, 538.0000, 494.2500, 479.0000, 542.5000],
         [452.5000, 587.5000, 323.2500, 461.7500, 278.0000],
         [673.7500, 391.2500, 615.5000, 237.2500, 656.5000]],

        [[415.5000, 429.2500, 574.7500, 663.2500, 474.5000],
         [310.2500, 631.7500, 495.0000, 630.0000, 321.0000],
         [602.5000, 396.5000, 345.0000, 722.2500, 221.7500]]])


# 10. Combining Tensor Operations

In [123]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.

In [124]:
tensor_a = torch.randint(100, (2, 3, 4))
tensor_b = torch.randint(100,(2, 3, 4))

print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)


Tensor A:
 tensor([[[50, 71, 82, 20],
         [31, 21, 23,  7],
         [23, 29, 84, 12]],

        [[53, 42, 53,  0],
         [ 9, 48, 20, 69],
         [12, 70, 35, 43]]])
Tensor B:
 tensor([[[44, 56, 58, 46],
         [14, 26, 10, 65],
         [10, 87, 45, 90]],

        [[85, 60, 87, 38],
         [83, 39, 31, 63],
         [80, 53, 61,  6]]])


In [125]:
# Add the two tensors.

In [126]:
tensor_add = torch.add(tensor_a, tensor_b)
print("Addition of tensor_a and tensor_b: ",tensor_add)

Addition of tensor_a and tensor_b:  tensor([[[ 94, 127, 140,  66],
         [ 45,  47,  33,  72],
         [ 33, 116, 129, 102]],

        [[138, 102, 140,  38],
         [ 92,  87,  51, 132],
         [ 92, 123,  96,  49]]])


In [127]:
# Multiply the resulting tensor by 2.

In [128]:
tensor_mul = torch.mul(tensor_a, tensor_b)
print("Multiplication of tensor_a and tensor_b: ",tensor_mul)

Multiplication of tensor_a and tensor_b:  tensor([[[2200, 3976, 4756,  920],
         [ 434,  546,  230,  455],
         [ 230, 2523, 3780, 1080]],

        [[4505, 2520, 4611,    0],
         [ 747, 1872,  620, 4347],
         [ 960, 3710, 2135,  258]]])


In [129]:
# Reshape the tensor to (4, 6).

In [130]:
print("tensor_mul shape: ", tensor_mul.shape)
tensor_reshaped = tensor_mul.reshape(4,6)
print("tensor_reshaped shape: ", tensor_reshaped.shape)


tensor_mul shape:  torch.Size([2, 3, 4])
tensor_reshaped shape:  torch.Size([4, 6])


In [131]:
# Compute the sum along the columns.

In [132]:
# Sum along columns (i.e., across rows → dim=0)
column_sum = tensor_reshaped.sum(dim=0)

print("Sum along columns: ", column_sum)

Sum along columns:  tensor([ 7555, 11298, 10557,  7153,  7096,  3756])


-------------------------------------------- END ----------------------------------------------