In [ ]:
# Sumani
# 22-7-2024

# Tensor Exercises

# 1. Tensor Creation

In [2]:
import torch

In [4]:
# Create a tensor of shape (2, 4) filled with ones.

In [6]:
one_t = torch.ones((2, 4))
print(one_t)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
# Create a tensor of shape (5, 3) filled with random values.

In [10]:
random_t = torch.rand((5, 3))
print(random_t)

tensor([[0.4634, 0.9978, 0.9005],
        [0.0970, 0.3756, 0.1402],
        [0.8521, 0.2165, 0.3525],
        [0.4548, 0.5381, 0.2697],
        [0.4772, 0.4799, 0.3825]])


In [ ]:
# Create a tensor from a list [5, 10, 15, 20].

In [12]:
list_t = torch.tensor([5,10,15,20])
print(list_t)

tensor([ 5, 10, 15, 20])


In [ ]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.

In [17]:
# rows = height = 6
# coulms = width = 8
# Channels = RGB

image_t = torch.rand(3,6,8)
print(image_t)

tensor([[[5.4488e-01, 5.8493e-01, 6.2084e-01, 6.7044e-01, 7.3666e-02,
          5.2384e-01, 1.3389e-01, 7.7757e-01],
         [9.2188e-01, 7.7385e-01, 9.2564e-01, 1.5287e-01, 8.7565e-01,
          6.1252e-01, 9.3934e-01, 7.4349e-02],
         [4.2523e-01, 3.8157e-01, 7.4506e-01, 1.1826e-01, 2.3307e-01,
          4.6049e-01, 4.0529e-01, 2.7416e-01],
         [4.8106e-01, 6.0133e-01, 1.2200e-01, 4.3767e-02, 1.5502e-01,
          1.2956e-01, 4.3354e-01, 5.9224e-01],
         [6.0220e-01, 2.4928e-02, 9.7615e-01, 6.0335e-01, 3.1997e-01,
          6.4643e-01, 8.0699e-01, 8.8137e-01],
         [7.1784e-01, 1.6565e-01, 1.3044e-01, 9.8919e-01, 3.9209e-02,
          5.4218e-01, 6.7130e-01, 1.9324e-01]],

        [[2.9037e-01, 3.8646e-01, 9.7543e-01, 6.5223e-01, 3.8586e-01,
          4.9153e-01, 2.0172e-01, 1.4991e-01],
         [7.1383e-02, 5.5062e-01, 8.0799e-01, 2.8153e-01, 7.3645e-01,
          4.0065e-01, 3.4036e-01, 1.7993e-01],
         [4.5781e-02, 2.1953e-01, 6.7736e-02, 4.5039e-01, 7.03

# 2. Tensor Indexing and Slicing

In [ ]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.


In [19]:
t_range = torch.arange(10, 22).reshape(3, 4)
print(t_range)

tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])


In [ ]:
# Access the element at the second row, third column.

In [27]:
# Index for the n-th position is always n-1 due to zero-based indexing

print("Element at the 2nd row, 3rd column: ", t_range[1,2])

Element at the 2nd row, 3rd column:  tensor(16)


In [ ]:
# Print the second row.

In [28]:
print("2nd row: ", t_range[1])

2nd row:  tensor([14, 15, 16, 17])


In [ ]:
# Print the first two columns.

In [31]:
#: selects all rows
#:2 selects columns at index 0 and 1 (the first two columns)

print("First two columns: ",t_range[:,:2])

First two columns:  tensor([[10, 11],
        [14, 15],
        [18, 19]])


# 3. Tensor Arithmetic Operations

In [ ]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random values.

In [10]:
tensor_a = torch.randint(1,100,(3,3))
tensor_b = torch.randint(1,100,(3,3))


print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)

Tensor A:
 tensor([[61, 19, 25],
        [44, 57,  1],
        [19, 78, 36]])
Tensor B:
 tensor([[38,  3,  7],
        [19, 44, 35],
        [95, 74, 97]])


In [ ]:
# Perform element-wise addition.

In [18]:
tensor_add = tensor_a + tensor_b
print("tensor_a + tensor_b = \n ", tensor_add)

tensor_add_2= torch.add(tensor_a, tensor_b)

print("tensor_a + tensor_b = \n ", tensor_add_2)


tensor_a + tensor_b = 
  tensor([[ 99,  22,  32],
        [ 63, 101,  36],
        [114, 152, 133]])
tensor_a + tensor_b = 
  tensor([[ 99,  22,  32],
        [ 63, 101,  36],
        [114, 152, 133]])


In [ ]:
# Perform element-wise multiplication.

In [21]:
tensor_mul = tensor_a * tensor_b
print("tensor_a x tensor_b = \n ", tensor_mul)

tensor_mul_2= torch.mul(tensor_a, tensor_b)
print("tensor_a x tensor_b = \n ", tensor_mul_2)


tensor_mul_3= torch.multiply(tensor_a, tensor_b)
print("tensor_a x tensor_b = \n ", tensor_mul_3)

tensor_a x tensor_b = 
  tensor([[2318,   57,  175],
        [ 836, 2508,   35],
        [1805, 5772, 3492]])
tensor_a x tensor_b = 
  tensor([[2318,   57,  175],
        [ 836, 2508,   35],
        [1805, 5772, 3492]])
tensor_a x tensor_b = 
  tensor([[2318,   57,  175],
        [ 836, 2508,   35],
        [1805, 5772, 3492]])


In [ ]:
# Subtract tensor_b from tensor_a.

In [23]:
tensor_sub = tensor_a - tensor_b
print("tensor_a - tensor_b = \n ", tensor_sub)

tensor_sub_2= torch.sub(tensor_a, tensor_b)

print("tensor_a - tensor_b = \n ", tensor_sub_2)

tensor_a - tensor_b = 
  tensor([[ 23,  16,  18],
        [ 25,  13, -34],
        [-76,   4, -61]])
tensor_a - tensor_b = 
  tensor([[ 23,  16,  18],
        [ 25,  13, -34],
        [-76,   4, -61]])


# 4. Tensor Aggregation Operations

In [ ]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.

In [35]:
tensor_agg = torch.arange(1, 10).reshape(3, 3)

print("tensor of shape (3, 3) with values ranging from 1 to 9: \n", tensor_agg)

tensor of shape (3, 3) with values ranging from 1 to 9: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
# Compute the sum of all elements.

In [43]:
sum = torch.sum(tensor_agg)
print("Sum =", sum.item())

Sum = 45


In [ ]:
# Compute the mean of all elements.

In [41]:
mean = tensor_agg.float().mean()
print("Mean :", mean.item())

Mean : 5.0


In [ ]:
# Find the maximum and minimum values.

In [42]:
max = tensor_agg.max()
print("max :", max.item())

max : 9


In [ ]:
# Compute the sum along the rows.

In [44]:
#dim=0: sum down the rows (column-wise)

#dim=1: sum across the columns (row-wise)

sum_rows = torch.sum(tensor_agg,dim=1)
print(sum_rows)

tensor([ 6, 15, 24])


In [ ]:
# Compute the mean along the columns.

In [52]:
print(tensor_agg)
mean_col = tensor_agg.float().mean(dim=0)
print("Mean along columns:\n", mean_col)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Mean along columns:
 tensor([4., 5., 6.])


# 5. Tensor Reshaping Operations

In [ ]:
# Create a tensor tensor of shape (2, 3, 4) with random values.

In [61]:
tensor_x = torch.randint(1000,(2,3,4))
print(tensor_x)

tensor([[[547, 958, 476, 234],
         [698, 629, 522,  29],
         [682, 315, 406, 376]],

        [[679, 101, 870, 919],
         [407, 900, 238, 651],
         [895, 613, 925, 777]]])


In [ ]:
# Reshape the tensor to (4, 6).

In [62]:
tensor_reshape = tensor_x.reshape(4,6)
print(tensor_reshape)

tensor([[547, 958, 476, 234, 698, 629],
        [522,  29, 682, 315, 406, 376],
        [679, 101, 870, 919, 407, 900],
        [238, 651, 895, 613, 925, 777]])


In [ ]:
# Transpose the tensor (swap the first and second dimensions).

In [66]:
tensor_transpose = tensor_reshape.T
print(tensor_transpose)

tensor_transpose2 = tensor_reshape.transpose(0, 1)
print(tensor_transpose2)

tensor([[547, 522, 679, 238],
        [958,  29, 101, 651],
        [476, 682, 870, 895],
        [234, 315, 919, 613],
        [698, 406, 407, 925],
        [629, 376, 900, 777]])
tensor([[547, 522, 679, 238],
        [958,  29, 101, 651],
        [476, 682, 870, 895],
        [234, 315, 919, 613],
        [698, 406, 407, 925],
        [629, 376, 900, 777]])


In [ ]:
# Flatten the tensor to a 1D tensor.

In [68]:
tensor_1d = tensor_transpose.reshape(24)
print(tensor_1d)

flattened = tensor_transpose.flatten()
print(flattened)


tensor([547, 522, 679, 238, 958,  29, 101, 651, 476, 682, 870, 895, 234, 315,
        919, 613, 698, 406, 407, 925, 629, 376, 900, 777])
tensor([547, 522, 679, 238, 958,  29, 101, 651, 476, 682, 870, 895, 234, 315,
        919, 613, 698, 406, 407, 925, 629, 376, 900, 777])


# 6. Tensor Broadcasting

In [ ]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.

In [70]:
tensor_a = torch.arange(1,7).reshape(2,3)
print(tensor_a)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].

In [75]:
tensor_b = torch.tensor([[1,2,3]])
print(tensor_b)
print(tensor_b.shape)

tensor([[1, 2, 3]])
torch.Size([1, 3])


In [ ]:
# Perform broadcasting addition.

In [76]:
# tensor_b gets broadcast to shape (2, 3)
# Broadcasting addition
# Last dimension: 3 and 3 → equal
# Second-to-last dimension: 2 and 1 →  one dimension is 1 → broadcastable

tensor_add = tensor_a + tensor_b
print("tensor_a + tensor_b = ",tensor_add)


tensor_a + tensor_b =  tensor([[2, 4, 6],
        [5, 7, 9]])


In [ ]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].

In [77]:
tensor_c = torch.tensor([1,2,3]).reshape(3,1)
print(tensor_c)

tensor([[1],
        [2],
        [3]])


In [ ]:
# Perform broadcasting multiplication.

In [81]:
#tensor_c: shape (3, 1) → broadcast to (3, 3)
#tensor_b: shape (1, 3) → broadcast to (3, 3)

result = tensor_b * tensor_c
print("Result:\n", result)

Result:
 tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])


# 7. Tensor Device Management

In [ ]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).

In [12]:
# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [13]:
# Create tensor and move to the appropriate device
tensor_gpu = torch.randint(100,(3,3)).to("cuda")
print(tensor_gpu)

tensor([[84, 26, 53],
        [ 3, 63, 75],
        [81, 71, 31]], device='cuda:0')


In [ ]:
# Verify if the tensor is on GPU.
# Move the tensor back to CPU.

In [5]:
print("Tensor on device:", tensor_gpu.device)

Tensor on device: cuda:0


In [9]:
tensor_cpu = tensor_gpu.to("cpu")
print("Tensor on device:", tensor_cpu.device)
print(tensor_cpu)


Tensor on device: cpu
tensor([[51, 21, 19],
        [19, 45, 83],
        [49, 67, 66]])


# 8. Tensor Cloning and Detaching

In [ ]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.

In [16]:
tensor_x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
print(tensor_x)

tensor([1., 2., 3.], requires_grad=True)


In [ ]:
# Clone the tensor and print the cloned tensor.

In [17]:
cloned_tensor = tensor_x.clone()
print("Cloned Tensor:", cloned_tensor)

Cloned Tensor: tensor([1., 2., 3.], grad_fn=<CloneBackward0>)


In [ ]:
# Detach the tensor from the computation graph and print the detached tensor.

In [19]:
detached_tensor = tensor_x.detach()
print("Detached Tensor:", detached_tensor)

Detached Tensor: tensor([1., 2., 3.])


# 9. High Dimensional Tensors

In [ ]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.

In [20]:
tensor_4d = torch.randint(1000,(2, 3, 4, 5))
print(tensor_4d)

tensor([[[[518, 384, 710, 368, 304],
          [ 94, 840, 278, 454, 566],
          [669, 408, 680, 194, 939],
          [772,  77, 452, 208, 561]],

         [[982, 832, 743, 930, 586],
          [429, 209, 876, 608, 723],
          [ 67, 358,  42, 590, 422],
          [771,  66, 545, 996,  40]],

         [[ 91, 190, 871, 214, 812],
          [573,  11, 597, 261, 951],
          [894, 928, 132,  85, 214],
          [221, 166, 965, 904,  14]]],


        [[[942, 882, 827, 674, 902],
          [ 72, 255, 771, 550, 433],
          [873, 827, 583, 100, 908],
          [709, 958, 758, 428, 222]],

         [[  3, 441, 377, 690, 994],
          [149, 974, 672, 658, 329],
          [979, 905, 384, 692, 297],
          [675, 492, 208, 535, 526]],

         [[727,  76,  62, 485, 263],
          [ 52, 589,   8, 659, 638],
          [259, 431,  61,  94, 318],
          [856, 190, 742, 367,  39]]]])


In [ ]:
# Print the shape of the tensor.

In [23]:
print(tensor_4d.shape)

torch.Size([2, 3, 4, 5])


In [ ]:
# Access the element at position (1, 2, 3, 4).

In [26]:
print("Element at position (1, 2, 3, 4): ", tensor_4d[1,2,3,4])

Element at position (1, 2, 3, 4):  tensor(39)


In [ ]:
# Slice and print the first two elements along the first dimension.

In [29]:
sliced = tensor_4d[:2]
print("Sliced Tensor (first two elements along dim 0):\n", sliced)

Sliced Tensor (first two elements along dim 0):
 tensor([[[[518, 384, 710, 368, 304],
          [ 94, 840, 278, 454, 566],
          [669, 408, 680, 194, 939],
          [772,  77, 452, 208, 561]],

         [[982, 832, 743, 930, 586],
          [429, 209, 876, 608, 723],
          [ 67, 358,  42, 590, 422],
          [771,  66, 545, 996,  40]],

         [[ 91, 190, 871, 214, 812],
          [573,  11, 597, 261, 951],
          [894, 928, 132,  85, 214],
          [221, 166, 965, 904,  14]]],


        [[[942, 882, 827, 674, 902],
          [ 72, 255, 771, 550, 433],
          [873, 827, 583, 100, 908],
          [709, 958, 758, 428, 222]],

         [[  3, 441, 377, 690, 994],
          [149, 974, 672, 658, 329],
          [979, 905, 384, 692, 297],
          [675, 492, 208, 535, 526]],

         [[727,  76,  62, 485, 263],
          [ 52, 589,   8, 659, 638],
          [259, 431,  61,  94, 318],
          [856, 190, 742, 367,  39]]]])


**sliced result is identical to the original tensor**

In [ ]:
# Sum all elements in the tensor.

In [30]:
total_sum = tensor_4d.sum()
print("Sum of all elements:", total_sum.item())


Sum of all elements: 59955


In [ ]:
# Compute the mean along the third dimension.

In [31]:
mean_dim3 = tensor_4d.float().mean(dim=2)
print("Mean along third dimension:\n", mean_dim3)


Mean along third dimension:
 tensor([[[513.2500, 427.2500, 530.0000, 306.0000, 592.5000],
         [562.2500, 366.2500, 551.5000, 781.0000, 442.7500],
         [444.7500, 323.7500, 641.2500, 366.0000, 497.7500]],

        [[649.0000, 730.5000, 734.7500, 438.0000, 616.2500],
         [451.5000, 703.0000, 410.2500, 643.7500, 536.5000],
         [473.5000, 321.5000, 218.2500, 401.2500, 314.5000]]])


# 10. Combining Tensor Operations

In [ ]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.

In [35]:
tensor_a = torch.randint(100, (2, 3, 4))
tensor_b = torch.randint(100,(2, 3, 4))

print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)


Tensor A:
 tensor([[[80, 67, 43, 77],
         [94, 24, 20, 43],
         [29, 31, 20, 42]],

        [[88,  1, 84, 87],
         [87, 26,  6, 98],
         [15, 83, 29, 87]]])
Tensor B:
 tensor([[[79, 41, 30, 99],
         [75, 51, 28, 61],
         [ 9, 81,  4, 24]],

        [[40, 84, 10, 82],
         [97, 80,  1, 99],
         [ 6, 93, 78, 44]]])


In [ ]:
# Add the two tensors.

In [37]:
tensor_add = torch.add(tensor_a, tensor_b)
print("Addition of tensor_a and tensor_b: ",tensor_add)

Addition of tensor_a and tensor_b:  tensor([[[159, 108,  73, 176],
         [169,  75,  48, 104],
         [ 38, 112,  24,  66]],

        [[128,  85,  94, 169],
         [184, 106,   7, 197],
         [ 21, 176, 107, 131]]])


In [ ]:
# Multiply the resulting tensor by 2.

In [38]:
tensor_mul = torch.mul(tensor_a, tensor_b)
print("Multiplication of tensor_a and tensor_b: ",tensor_mul)

Multiplication of tensor_a and tensor_b:  tensor([[[6320, 2747, 1290, 7623],
         [7050, 1224,  560, 2623],
         [ 261, 2511,   80, 1008]],

        [[3520,   84,  840, 7134],
         [8439, 2080,    6, 9702],
         [  90, 7719, 2262, 3828]]])


In [ ]:
# Reshape the tensor to (4, 6).

In [40]:
print("tensor_mul shape: ", tensor_mul.shape)
tensor_reshaped = tensor_mul.reshape(4,6)
print("tensor_reshaped shape: ", tensor_reshaped.shape)


tensor_mul shape:  torch.Size([2, 3, 4])
tensor_reshaped shape:  torch.Size([4, 6])


In [ ]:
# Compute the sum along the columns.

In [42]:
# Sum along columns (i.e., across rows → dim=0)
column_sum = tensor_reshaped.sum(dim=0)

print("Sum along columns: ", column_sum)

Sum along columns:  tensor([10406, 15156,  2481, 24987, 17831,  8140])


-------------------------------------------- END ----------------------------------------------